export const IMAGE_SEARCH = {
    REQUEST:"IMAGE_SEARCH_REQUEST",
    SUCCESS:"IMAGE_SEARCH_SUCCESS",
    ERROR:"IMAGE_SEARCH_ERROR",
}

export const IMAGE_DETAILS = {
    REQUEST:"IMAGE_DETAILS_REQUEST",
    SUCCESS:"IMAGE_DETAILS_SUCCESS",
    ERROR:"IMAGE_DETAILS_ERROR",
}